language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.3
  - 2.4.1
gemfile:
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_3_1.gemfile
  - gemfiles/rails_3_0.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails_3_0.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails_3_1.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails_3_2.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_3_0.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_3_1.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_3_2.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4_1.gemfile
before_install: gem update bundler
sudo: false
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS unread_test;'; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database unread_test;' -U postgres; fi"
