sqlite:
  adapter: sqlite3
  database: ":memory:"
mysql:
  adapter: mysql2
  database: unread_test
  username: root
  encoding: utf8
postgres:
  adapter: postgresql
  database: unread_test
  username: postgres
